module: Kodio
title: Kodio
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/kodio/
min_acl: private
clean: true
theme: apple
build_tool_arguments: -target,"Kodio (macOS)",-sdk,macosx
