module: Kodio
title: Kodio
author: Nick Berendsen
author_url: https://desbeers.nl
github_url: https://github.com/desbeers/kodio/
min_acl: private
clean: true
theme: apple

# Command line for doc generation:
# jazzy --xcodebuild-arguments -target,"Kodio (macOS)"
